# Generated by Django 6.0.4 on 2026-04-16 14:00

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('kind', models.CharField(choices=[('generic', 'Изображение'), ('hero-portrait', 'Портрет героя')], default='generic', max_length=50, verbose_name='Тип')),
                ('image', models.ImageField(height_field='height', upload_to=content.models.asset_image_upload_to, verbose_name='Файл изображения', width_field='width')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Высота')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Ассет',
                'verbose_name_plural': 'Ассеты',
                'ordering': ('kind', 'order', 'title'),
            },
        ),
    ]
