# Generated by Django 6.0.4 on 2026-04-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(
                choices=[
                    ('generic', 'Изображение'),
                    ('hero-portrait', 'Портрет героя'),
                    ('page-icon', 'Иконка страницы'),
                ],
                default='generic',
                max_length=50,
                verbose_name='Тип',
            ),
        ),
    ]
