# Generated by Django 6.0.4 on 2026-04-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_asset'),
        ('heroes', '0003_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='portrait',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'hero-portrait'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes', to='content.asset', verbose_name='Портрет'),
        ),
    ]
