# Generated by Django 6.0.4 on 2026-04-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_hero_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropage',
            name='icon_key',
            field=models.CharField(
                blank=True,
                choices=[
                    ('overview', 'Overview / Main'),
                    ('start', 'Start'),
                    ('progression', 'Progression / Build'),
                    ('reference', 'Reference'),
                    ('tips', 'Tips'),
                    ('mistakes', 'Mistakes'),
                    ('tactics', 'Tactics / Strategy'),
                    ('traits', 'Traits / Skills'),
                    ('dice', 'Dice'),
                    ('encounters', 'Encounters'),
                    ('synergies', 'Synergies'),
                    ('leveling', 'Leveling'),
                    ('faq', 'FAQ'),
                    ('tracker', 'Tracker'),
                    ('checklist', 'Checklist'),
                    ('route', 'Route / Plan'),
                    ('notes', 'Notes'),
                    ('setup', 'Setup / Prep'),
                    ('stats', 'Stats'),
                    ('default', 'Default'),
                ],
                default='',
                max_length=32,
                verbose_name='Иконка страницы',
            ),
        ),
    ]
