# Generated by Django 6.0.4 on 2026-04-16 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_asset_kind_add_page_icon'),
        ('heroes', '0005_heropage_icon_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropage',
            name='icon',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'kind': 'page-icon'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hero_pages_with_icon',
                to='content.asset',
                verbose_name='Иконка страницы',
            ),
        ),
        migrations.AlterField(
            model_name='heropage',
            name='icon_key',
            field=models.CharField(
                blank=True,
                default='',
                max_length=32,
                verbose_name='Legacy fallback icon key',
            ),
        ),
    ]
