# Generated by Django 6.0.4 on 2026-04-16 21:45

from django.db import migrations
from django.utils.text import slugify


BUILTIN_ICON_DEFINITIONS = [
    ('overview', 'Overview / Main', 'Иконка страницы Overview / Main', 10, 'assets/page-icon/overview/overview.png'),
    ('start', 'Start', 'Иконка страницы Start', 20, 'assets/page-icon/start/start.png'),
    ('progression', 'Progression / Build', 'Иконка страницы Progression / Build', 30, 'assets/page-icon/progression/progression.png'),
    ('reference', 'Reference', 'Иконка страницы Reference', 40, 'assets/page-icon/reference/reference.png'),
    ('tips', 'Tips', 'Иконка страницы Tips', 50, 'assets/page-icon/tips/tips.png'),
    ('mistakes', 'Mistakes', 'Иконка страницы Mistakes', 60, 'assets/page-icon/mistakes/mistakes.png'),
    ('tactics', 'Tactics / Strategy', 'Иконка страницы Tactics / Strategy', 70, 'assets/page-icon/tactics/tactics.png'),
    ('traits', 'Traits / Skills', 'Иконка страницы Traits / Skills', 80, 'assets/page-icon/traits/traits.png'),
    ('dice', 'Dice', 'Иконка страницы Dice', 90, 'assets/page-icon/dice/dice.png'),
    ('encounters', 'Encounters', 'Иконка страницы Encounters', 100, 'assets/page-icon/encounters/encounters.png'),
    ('synergies', 'Synergies', 'Иконка страницы Synergies', 110, 'assets/page-icon/synergies/synergies.png'),
    ('leveling', 'Leveling', 'Иконка страницы Leveling', 120, 'assets/page-icon/leveling/leveling.png'),
    ('faq', 'FAQ', 'Иконка страницы FAQ', 130, 'assets/page-icon/faq/faq.png'),
    ('tracker', 'Tracker', 'Иконка страницы Tracker', 140, 'assets/page-icon/tracker/tracker.png'),
    ('checklist', 'Checklist', 'Иконка страницы Checklist', 150, 'assets/page-icon/checklist/checklist.png'),
    ('route', 'Route / Plan', 'Иконка страницы Route / Plan', 160, 'assets/page-icon/route/route.png'),
    ('notes', 'Notes', 'Иконка страницы Notes', 170, 'assets/page-icon/notes/notes.png'),
    ('setup', 'Setup / Prep', 'Иконка страницы Setup / Prep', 180, 'assets/page-icon/setup/setup.png'),
    ('stats', 'Stats', 'Иконка страницы Stats', 190, 'assets/page-icon/stats/stats.png'),
    ('default', 'Default', 'Иконка страницы Default', 200, 'assets/page-icon/default/default.png'),
]

ICON_ALIASES = {
    'overview': 'overview',
    'menu': 'overview',
    'main': 'overview',
    'home': 'overview',
    'start': 'start',
    'begin': 'start',
    'intro': 'start',
    'progression': 'progression',
    'progress': 'progression',
    'build': 'progression',
    'reference': 'reference',
    'ref': 'reference',
    'tips': 'tips',
    'tip': 'tips',
    'mistakes': 'mistakes',
    'mistake': 'mistakes',
    'errors': 'mistakes',
    'error': 'mistakes',
    'tactics': 'tactics',
    'tactic': 'tactics',
    'strategy': 'tactics',
    'strategies': 'tactics',
    'traits': 'traits',
    'trait': 'traits',
    'skills': 'traits',
    'skill': 'traits',
    'dice': 'dice',
    'die': 'dice',
    'encounters': 'encounters',
    'encounter': 'encounters',
    'battle': 'encounters',
    'synergies': 'synergies',
    'synergy': 'synergies',
    'teamwork': 'synergies',
    'leveling': 'leveling',
    'level': 'leveling',
    'faq': 'faq',
    'questions': 'faq',
    'tracker': 'tracker',
    'track': 'tracker',
    'checklist': 'checklist',
    'check': 'checklist',
    'route': 'route',
    'plan': 'route',
    'path': 'route',
    'notes': 'notes',
    'note': 'notes',
    'setup': 'setup',
    'prep': 'setup',
    'preparation': 'setup',
    'stats': 'stats',
    'stat': 'stats',
    'default': 'default',
}


def normalize_icon_token(value: str) -> str:
    return slugify(value or '').replace('-', '_').strip('_')


def split_tokens(value: str) -> list[str]:
    normalized = slugify(value or '').replace('-', ' ')
    return [part for part in normalized.split() if part]


def resolve_icon_key(page) -> str:
    candidates = [getattr(page, 'icon_key', ''), getattr(page, 'code', ''), getattr(page, 'slug', ''), getattr(page, 'title', '')]

    for raw_value in candidates:
        normalized = normalize_icon_token(raw_value)
        if normalized in ICON_ALIASES:
            return ICON_ALIASES[normalized]

        for token in split_tokens(raw_value):
            normalized_token = normalize_icon_token(token)
            if normalized_token in ICON_ALIASES:
                return ICON_ALIASES[normalized_token]

    return 'default'


def seed_page_icon_assets(apps, schema_editor):
    Asset = apps.get_model('content', 'Asset')
    HeroPage = apps.get_model('heroes', 'HeroPage')

    icon_assets = {}
    for slug, title, alt, order, image_path in BUILTIN_ICON_DEFINITIONS:
        asset, _ = Asset.objects.get_or_create(
            slug=f'page-icon-{slug}',
            defaults={
                'title': title,
                'kind': 'page-icon',
                'image': image_path,
                'alt': alt,
                'width': 128,
                'height': 128,
                'order': order,
                'is_published': True,
            },
        )
        if asset.kind != 'page-icon':
            asset.kind = 'page-icon'
            asset.save(update_fields=['kind'])

        icon_assets[slug] = asset

    for page in HeroPage.objects.all():
        icon_key = resolve_icon_key(page)
        asset = icon_assets.get(icon_key) or icon_assets['default']
        page.icon_id = asset.pk
        if not page.icon_key:
            page.icon_key = icon_key
            page.save(update_fields=['icon', 'icon_key'])
        else:
            page.save(update_fields=['icon'])


def unseed_page_icon_assets(apps, schema_editor):
    Asset = apps.get_model('content', 'Asset')
    HeroPage = apps.get_model('heroes', 'HeroPage')

    HeroPage.objects.update(icon=None)
    Asset.objects.filter(kind='page-icon', slug__startswith='page-icon-').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_heropage_icon_asset'),
        ('content', '0003_alter_asset_kind_add_page_icon'),
    ]

    operations = [
        migrations.RunPython(seed_page_icon_assets, unseed_page_icon_assets),
    ]
